FROM registry.access.redhat.com/rhel7/rhel:7.3-53

COPY etc /etc
COPY usr /usr

ENV CATALINA_HOME /opt/tomcat
ENV PATH $CATALINA_HOME/bin:$PATH

RUN yum -y update; yum clean all
RUN yum -y install nano;
RUN yum -y install wget;
RUN wget -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/11+28/55eed80b163941c8885ad9298e6d786a/j$
RUN yum -y install jdk-11_linux-x64_bin.rpm
RUN java --version
RUN useradd tomcat
RUN mkdir /opt/tomcat
RUN wget http://apache.spinellicreations.com/tomcat/tomcat-9/v9.0.12/bin/apache-tomcat-9.0.12.tar.gz
RUN tar -zxvf apache-tomcat-9.0.12.tar.gz -C /opt/tomcat --strip-components=1
RUN cd /opt && chown -R tomcat tomcat/
RUN chmod 777 /etc/systemd/system
RUN echo $"[Unit] Description=Apache Tomcat Web Application\Container After=syslog.target network.target\[Service]\Type=forking\Environment=JAVA_HOME=/usr/l$
RUN chmod 777 -R /opt/tomcat/webapps/manager/META-INF
RUN cd /opt/tomcat/webapps/manager/META-INF/
RUN echo $"<?xml version=\"1.0\" encoding=\"UTF-8\"?><Context antiResourceLocking=\"false\" privileged=\"true\"><Manager sessionAttributeValueClassNameFilte$
RUN cd /opt/tomcat/conf
RUN echo $"<?xml version=\"1.0\" encoding=\"UTF-8\"?><tomcat-users xmlns=\"http://tomcat.apache.org/xml\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-insta$
EXPOSE 8080
CMD ["catalina.sh", "run"] 